### ISSUE TITLE
ansi colours

### ISSUE THREAD

**Issue by fommil** [ensime/emacs-sbt-mode#100]
maybe we should be using this to get the auto colouring https://www.emacswiki.org/emacs/AnsiColor

then we only need to parse for error messages with files/lines

**Comment by hvesalai** [comment]
I thought we were. What would you change exactly?

**Comment by fommil** [comment]
we just ignore the ansi colours, or disable sbt from outputting them. I'm pretty sure when I used the nutest framework (was popular for scalajs a few years ago) it spat out ansi colours and we didn't deal with them. I think it's as simple as enabling a comint mode to be honest. But then we need to make sbt / scalatest etc output the escapes again.

**Comment by hvesalai** [comment]
At least my intention was that we use the `ansi-color.el` as can be seen on line https://github.com/ensime/emacs-sbt-mode/blob/master/sbt-mode-comint.el#L79

Have you set `sbt:ansi-support` to `t` ?

**Comment by fommil** [comment]
argh! I had it set to `filter`

**Comment by fommil** [comment]
hmm, if I set it to `t` and run `test` (after restarting `sbt`) I don't get any ansi colours in the scalatest output (in this particular project the regexes don't match, which is what got me thinking about ansi colours).

**Comment by fommil** [comment]
I wonder if `sbt:ansi-filter` is interfering

**Comment by fommil** [comment]
now that I pay real close attention, I can see the colours coming up correctly for a flash, and then they get reset to blank. Very strange. I think we have a regression here, I will try to get to the bottom of it.

**Comment by hvesalai** [comment]
One idea for debugging is to turn compilation mode off. It might interfere.

**Comment by fommil** [comment]
I'm pretty sure `compilation-mode` is doing this, colours appear when it's disabled. Somebody already asked the question at https://emacs.stackexchange.com/questions/24698 but no solution I can see.

**Comment by fommil** [comment]
doh! First post was the answer, of course! http://endlessparentheses.com/ansi-colors-in-the-compilation-buffer-output.html

OK, this just needs to be done when it bothers me enough on a rainy day.

**Comment by fommil** [comment]
#115 has some extra useful info... looks like our use of ansi regex no longer supports latest emacs anyway.

**Comment by fommil** [comment]
I think I figured it out, it's a bug in jline! I sent them a PR here https://github.com/jline/jline2/pull/285 but I'm looking into a workaround.
