### ISSUE TITLE
support sbt-errors-summary

### ISSUE THREAD

**Issue by fommil** [ensime/emacs-sbt-mode#113]
https://github.com/Duhemm/sbt-errors-summary breaks the format of compiler reporting and might become the default in sbt 1.0. This ticket is to add regexes to support it, although note that unless https://github.com/Duhemm/sbt-errors-summary/issues/13 is implemented, there will be an unrecoverable regression.

Hopefully there will also be an option to simply revert to the old style error reporting.

**Comment by VlachJosef** [comment]
I've tested today `sbt-errors-summary` sbt plugin and to my surprise it doesn't break when relative file paths are used. Which is actually great as it means less clutter in sbt output.

**Comment by fommil** [comment]
`compilation-mode` will use best guesses for relative paths, but it will fail if you have multiple projects open at the same time (which I often do, different project per open PR, often 3 or 4).

**Comment by fommil** [comment]
with regards to less clutter, we could support that ourselves... just by grabbing the full path and rendering it as relative (or somehow shortened). I'd be surprised if there isn't a package for that already.

**Comment by VlachJosef** [comment]
So I just make a clone of one project into different directory to test multiple project with identical directory structure and `compilation-mode` handles that without problems.

If it should really under some circumstances cause any problems, there will always be an option to turn on full path. Regex from #114 supports both.
