### ISSUE TITLE
JLineCompletion error

### ISSUE THREAD

**Issue by fommil** [ensime/emacs-sbt-mode#117]
this from a simple 2.12 session...

```
Welcome to Scala 2.12.2 (OpenJDK 64-Bit Server VM, Java 1.8.0_141).
Type in expressions for evaluation. Or try :help.

scala> val foo = "foo"
foo: String = foo
ntp).completer; val completions = completer.complete(input, input.length); val prefix = input.substring(0, completions.cursor); completions.candidates.foreach(c => println("[completions] " + c))} // completions
<console>:13: error: type JLineCompletion is not a member of package scala.tools.nsc.interpreter
       { val input = "fo"; val completer = new scala.tools.nsc.interpreter.JLineCompletion($intp).completer; val completions = completer.complete(input, input.length); val prefix = input.substring(0, completions.cursor); completions.candidates.foreach(c => println("[completions] " + c))} // completions
                                                                           ^
```

**Comment by fommil** [comment]
I think I'm going crazy, I definitely remember sitting down with @JulesGosnell a few years ago and hacking in TAB completion (via some god awful `advice` hacks at the `comint` layer) by tricking the REPL into thinking we were in a normal terminal. But I can't for the life of me find that code either here or in `ensime-emacs`. Maybe we never pushed it?

**Comment by zwild** [comment]
I get this error too..

**Comment by hvesalai** [comment]
This has nothing to do with the TAB completion you have implemented. It is my code. What it does is it sends that awfully long line to the REPL to be interpreted, with your input as a String. However, unexpected echo of the line is preventing comint from parsing the completions.

**Comment by hvesalai** [comment]
And in this case the command being sent doesn't seem to work. Maybe it only works when run from within sbt?
