### ISSUE TITLE
support sbt-errors-summary

### ISSUE THREAD

**Issue by fommil** [ensime/emacs-sbt-mode#118]
@VlachJosef's two additions to https://github.com/ensime/emacs-sbt-mode/blob/master/sbt-mode.el#L210-L225 (`sbt:initialize-for-compilation-mode`) are not resulting in clickable links for me in 0.4.1. Of course we have no chance in 0.5.0 because of https://github.com/Duhemm/sbt-errors-summary/issues/30

When updating these regexes we should document what they are, i.e. a link to an example line and if it is for a plugin.

**Comment by VlachJosef** [comment]
To get clickable links with 0.4.1 you need to allow columns information.

I have this in my `~/.sbt/0.13/global.sbt`

```
import sbt.errorssummary.Plugin.autoImport._

reporterConfig := reporterConfig.value.withColumnNumbers(true)
```

**Comment by fommil** [comment]
we should probably support it "out of the box" too

**Comment by fommil** [comment]
should we remove our column parsing hack in light of this? Or maybe we could have an emacs reporter plugin that does stock reporting with column numbers, opt-in.

**Comment by VlachJosef** [comment]
I would remove column parsing hack, as it is ugly and doesn't work reliable in some cases.
Those people affected can always opt for using sbt-errors-summary plugin. In version 0.4.1 it really gives good results.
I don't see need for our own emacs reporter plugin as of yet. Hopefully once https://github.com/Duhemm/sbt-errors-summary/issues/30 is resolved it will keep providing good service to us.

**Comment by fommil** [comment]
ok, that sounds good
