### ISSUE TITLE
Invalid system property 'jline.terminal' when using sbt-start on windows.

### ISSUE THREAD

**Issue by MC-Escherichia** [ensime/emacs-sbt-mode#120]
When I run sbt-start on my project, as well as a simple project created with `scala new scala/hello-world.g8`, I get the following print out. 

    Warning: invalid system property 'jline.terminal'
    [info] Loading global plugins from C:\Users\mcescherichia\.sbt\0.13\plugins
    [info] Loading project definition from C:\Users\mcescherichia\Code\sbt-start-test\project
    [info] Set current project to hello-world (in build file:/C:/Users/mcescherichia/Code/sbt-start-test/)
    [error] No valid parser available.
    [error] jline.UnsupportedTerminal
    [error]       ^
    Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0`

When I run sbt in my console everything works as it should. I'm on Windows 7, emacs 25.2.1

**Comment by fommil** [comment]
@MC-Escherichia probably nobody else here cares about Windows right now. Can you please have a look at the initialisation logic and see if there is an easy fix?

From memory, when I was on Windows, we needed to add the values contained in the defaults for `sbt:program-options`. But we may be applying those incorrectly or you might not be using a recent official `sbt.bat` from Lightbend (there are many home-rolled versions available).

**Comment by fommil** [comment]
I cannot reproduce on GNU/Linux by setting the windows values

```
(setq sbt:program-options '("-Djline.terminal=jline.UnsupportedTerminal"))
```

indeed, it uses the unsupported (non-ansi) terminal if I do this.

**Comment by MC-Escherichia** [comment]
Thanks for pointing me in the right direction. Running 

    (setq sbt:program-options '()) 

allows me to run sbt with a warning that display-shell-version is unsupported, but other than that it functions fine.

**Comment by fommil** [comment]
where did you get your sbt script from? It sounds broken

**Comment by MC-Escherichia** [comment]
I downloaded the msi installer from scala-sbt.org for version 0.13, then 1.0 when I started receiving this error.

**Comment by fommil** [comment]
Maybe we don't need the arg anymore since we worked around a bug in jline.

**Comment by fommil** [comment]
Do you get full colours? e.g. when running tests?

**Comment by bennythomps** [comment]
That at least gets rid of the warning for me, but after removing the property, I don't get any output but a little startup logging:
```
[info] Loading project definition from C:\src\mystuff\project
[info] Set current project to mystuff (in build file:/C:/src/mystuff/)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
```

**Comment by fommil** [comment]
I think the windows sbt launcher is broken upstream :-/

**Comment by bennythomps** [comment]
looks like adding `SBT_OPTS=-Djline.terminal=jline.UnsupportedTerminal` before sbt runs makes things move forward. Still no colors and returns to an sbt prompt after the command runs, but it's at least progress!
