### ISSUE TITLE
move to gitlab

### ISSUE THREAD

**Issue by fommil** [ensime/emacs-sbt-mode#123]
I'd like to move this repo over to gitlab, but I'll only do it if @VlachJosef and @hvesalai agree. I've been trying it out recently and it has some features that make it better than github, e.g. integrated CI, free/libre license, more detailed settings (e.g. finer grain branch protection).

- [ ] copy over repo and issues (automated)
- [ ] max permissions to @VlachJosef and @hvesalai
- [ ] set up new CI pipeline
- [ ] switch melpa to point to new repo
- [ ] update docs

**Comment by hvesalai** [comment]
What is the reason for the move? What are the pros and cons of doing it?

**Comment by fommil** [comment]
the CI is much better and saves me money because I don't have to host a drone server. That's mostly relevant for the ensime server, but I think it'd be nice if everything moved over together.

I think gitlab is also becoming the favourite for emacs-lisp packages in general. I've seen a lot of the top emacs contributors move over in the last year. This is probably because the FSF gave it the thumbs up whilst giving github the thumbs down.

**Comment by hvesalai** [comment]
Ok. I'm fine with the move. What do I have to do?

**Comment by fommil** [comment]
Nothing :-) well, maybe log in to gitlab and use the same username and I'll find you when I do this. You can use your github oauth so you don't even need a new password.

**Comment by VlachJosef** [comment]
I'm also ok with the move.

**Comment by fommil** [comment]
nah, just swapping CI to use @chipsenkbeil's machine
