### ISSUE TITLE
support 1.0 source error report column

### ISSUE THREAD

**Issue by fommil** [ensime/emacs-sbt-mode#126]
@VlachJosef is it time to unleash the column support? :smile: 

```
[info] Compiling 1 Scala source to /tmp/fommil-sbt/home/fommil/Projects/stalactite/target/scala-2.12/classes ...
[error] /home/fommil/Projects/stalactite/src/main/scala/scalaz/Default.scala:102:23: type mismatch;
[error]  found   : y.type (with underlying type Y)
[error]  required: Y
[error]               ev2.inj(y)
[error]                       ^
```

note that the column info is present (although there might be a count-from-zero vs count-from-one issue). We're currently not seeing the column.

**Comment by VlachJosef** [comment]
Here is PR #127 with Sbt 1.0 support. 

Count-from-zero vs count-from-one shouldn't be an issue, I paid attention to that while implementing column support in sbt :eagle:
