### ISSUE TITLE
Per-project sbt:program-name

### ISSUE THREAD

**Issue by ag91** [ensime/emacs-sbt-mode#129]
Hi,

Thanks very much for maintaining this mode: it is very great to work in Scala within Emacs!

The issue: I work on several projects and some of them requires a custom sbt.
I tried to solve this setting sbt:program-name per project by using the wonderful directory variables [1], 
but unluckily running a command through shortcuts on a file in the directory
does not pick the correct sbt.

I was wondering if anybody already solved the same problem, or has better ways to set this variable locally. 
Otherwise I can dive into the code and see if there is an issue in the code.

[1] https://www.emacswiki.org/emacs/DirectoryVariables

**Comment by hvesalai** [comment]
You could externalize this problem from emacs to a shell script that starts the sbt that is needed based on the $CMD variable

**Comment by ag91** [comment]
@hvesalai hey that is a nice idea I did not think about! I can surely solve my problem with it. Thanks!
However I would prefer to do it from Emacs itself (I really like the directory variable mechanism!) :P

**Comment by ag91** [comment]
I came up with an Emacs solution:

``` elisp
(defun get-to-parent-until (fn dir)
  "Returns the first directory from DIR that satisfies FN or NIL."
  (let ((current dir))
    (while (not (or (equalp current "/") 
                    (funcall fn current)))
      (setq current (expand-file-name (concat current "/.."))))
    (if (funcall fn current)
        current
      nil)))

(defun set-sbt-program ()
  "Sets ensime ans sbt program name to local if it exists"
  (interactive)
  (let* ((sbt-dir (get-to-parent-until
                   #'(lambda (d)
                       (file-exists-p  (concat d "/sbt")))
                   default-directory))
         (exec (if sbt-dir (concat sbt-dir "/sbt") "sbt")))
    (setq ensime-sbt-command exec
          sbt:program-name exec)))

(add-hook 'ensime-mode-hook #'set-sbt-program)

```
I am closing this.
Thanks for the help.
