### ISSUE TITLE
Turn echo off for all sbt-mode interactions

### ISSUE THREAD

**Issue by hvesalai** [ensime/emacs-sbt-mode#132]
Both sbt and the REPL console started from within sbt have echo turned on when running from emacs.

This needs to change.

1. create a new command `emacs` for emacs use instead of `shell`. Here it is... 

```
import java.io.InputStreamReader
import sbt.BasicKeys.shellPrompt

val Emacs = "emacs"
def emacs = Command.command(Emacs) { s =>
  val prompt = (s get shellPrompt) match { case Some(pf) => pf(s); case None => "> " }
  System.out.print(prompt)
  val reader = new InputStreamReader(System.in)
  val first = reader.read
  val line = if (first == -1) None else {
    Some((Iterator.single(first) ++ Iterator.continually(reader.read)).takeWhile(c => !(c == -1 || c == '\n')).map(_.toChar).mkString)
  }

  line match {
    case Some(line) =>
      val newState = s.copy(onFailure = Some(Emacs), remainingCommands = line +: Emacs +: s.remainingCommands).setInteractive(true)
      if (line.trim.isEmpty) newState else newState.clearGlobalLog
    case None => s.setInteractive(false)
  }
}

commands += emacs
```

Until we have that in the main sbt release, people can place it in `~/.sbt/0.13/Emacs.sbt` and modify `sbt:program-options` custom setting to run the command when starting sbt. 

2. The second thing is to do the same for the REPL, i.e. console. Currently the REPL has echo hardcoded in scala 2.12, but not in 2.13 

For 2.12. there are two options here:
a) modify the REPL (i.e. submit patch to `scala`) it self to read some system variable and not echo if that variable is set: here [SimpleReader.scala#L28](https://github.com/scala/scala/blob/v2.12.3/src/repl/scala/tools/nsc/interpreter/SimpleReader.scala#L28)

b) modify sbt so that it doesn't create the default, echoing, version of the repl. This happens here for scala 2.11 and 2.12: https://github.com/sbt/zinc/blob/1.x/internal/compiler-bridge/src/main/scala_2.11-12/xsbt/ConsoleInterface.scala#L44

For 2.13 it has already been implemented: just set [env.emacs](https://github.com/scala/scala/blob/07d61ecf134dbba143531f5a1bd3c1289c437296/src/compiler/scala/tools/nsc/Properties.scala#L32) to `true` (or any non-empty value)

3. After the both step has been done, `sbt-mode-comint.el` should be modified so that `comint-process-echoes` is set to `nil` insteadof the current `t`.

**Comment by hvesalai** [comment]
ping @fommil

**Comment by fommil** [comment]
we could include this in `sbt-ensime`

**Comment by hvesalai** [comment]
For sbt 1.1 the thing has changed completely in commit e83564a6

**Comment by hvesalai** [comment]
But I guess the same thing could still work, since they do have an `oldShell` akin to `emacs` in there https://github.com/sbt/sbt/blob/a0b27d29b72f7177a63bc83b32040dad5db8bfc4/main-command/src/main/scala/sbt/BasicCommands.scala#L252

**Comment by hvesalai** [comment]
For both 0.13.x and 1.x we should have sbt follow the env.emacs variable and create a SimpleReader instead of FullReader. I'll make PRs to sbt

**Comment by hvesalai** [comment]
Also, we should try to get `scala` REPL to include a `:completions` command

**Comment by hvesalai** [comment]
https://github.com/sbt/sbt/pull/3982

**Comment by hvesalai** [comment]
I was wrong

**Comment by hvesalai** [comment]
See also #136 #134 #135
