### ISSUE TITLE
errors when initializing? 

### ISSUE THREAD

**Issue by danyaljj** [ensime/emacs-sbt-mode#35]
It seems like I am getting errors in the first run after I add the definitions of sbt-mode into my `.emacs` file: 
![sbt-mode1](https://cloud.githubusercontent.com/assets/2441454/11759687/4039b666-a046-11e5-8e22-797d45624ac3.png)

![sbt-mode2](https://cloud.githubusercontent.com/assets/2441454/11759686/3efa3366-a046-11e5-8b35-131af5d30721.png)

And when I run `M-x sbt-start` here is what I get: 
![sbt-mode3](https://cloud.githubusercontent.com/assets/2441454/11759684/35aea382-a046-11e5-8ed0-39655cef096d.png)

Any ideas? 
Here is my emacs  version: 

```
[khashab2@silverbridge ~]$ emacs --version
GNU Emacs 24.2.2
Copyright (C) 2012 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by hvesalai** [comment]
I'm using 
```
GNU Emacs 24.3.1
Copyright (C) 2013 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by hvesalai** [comment]
And it seems `defvar-local` is new in emacs 24.3, so that's the reason. You would need to upgrade your emacs.
