### ISSUE TITLE
`Lisp error: (wrong-type-argument stringp nil)` when root cannot be determined

### ISSUE THREAD

**Issue by hvesalai** [ensime/emacs-sbt-mode#41]
If you run `sbt-start` in a directory where the `sbt:root` cannot be determined (i.e. it returns `nil`), the error in the subject is shown to the user. This is not very helpful. Instead a proper error message should be shown instructing the user to set run the command in the proper directory (or set a project properly).

**Comment by Hodapp87** [comment]
I just ran into this also, and it's a very cryptic error to receive with no explanation.
