### ISSUE TITLE
Lisp error: (void-variable sbt:prefer-nested-projects)

### ISSUE THREAD

**Issue by hvesalai** [ensime/emacs-sbt-mode#42]
Related to #37, I get this error when trying to use `sbt-find-definitions` before running sbt.

```
Debugger entered--Lisp error: (void-variable sbt:prefer-nested-projects)
  sbt:find-root-impl("project/build.properties" "~/projects/foo/" nil)
```

The function should be written so that it doesn't expect `sbt:prefer-nested-projects` to be defined.

**Comment by fommil** [comment]
how are you loading `sbt-mode` because this is defined as a defcustom in `sbt-mode.el`

**Comment by fommil** [comment]
It would be a shame to have to move this `defcustom` into `sbt-mode-project.el`.

Maybe we could have a `sbt-vars.el` and put all the `defcustom`s into there, then depend on it from all the individual files.

**Comment by hvesalai** [comment]
In this case I hadn't yet loaded sbt-mode. And I think that's a valid use case since sometimes I use `sbt-find-definitions` and other grep commands before launching sbt.
