### ISSUE TITLE
Windows properties

### ISSUE THREAD

**Issue by fommil** [ensime/emacs-sbt-mode#44]
maybe we could automate some of https://github.com/ensime/ensime.github.io/issues/40 to be windows friendly

**Comment by VyacheslavMik** [comment]
I fully support this request. May be I can add this info in this [documentation](http://ensime.github.io/editors/emacs/install/). I spent many times in exploring how to force `sbt` work in `emacs` on Windows, but failed, until @fommil help me.

**Comment by fommil** [comment]
@VyacheslavMik the point of this ticket is to automate it so that it doesn't need to be documented in the first place. How's your elisp? Would you like to help out to implement this? It might be as simple as adding the `jline.terminal` to `SBT_OPTS` prior to starting the `sbt` executable. It might even be a useful thing for Linux / OSX as well, since we can't handle any fancy ASCII colour characters in Emacs.

**Comment by VyacheslavMik** [comment]
@fommil I write on `Common Lisp` a little. I may try on this weekend, but I never work with `github`. Anyone may change source code?

**Comment by fommil** [comment]
@VyacheslavMik click the fork button on the repo (this is typically called the "upstream" repo), then you get your own repository (typically called the "origin") which you can clone locally. Then push your changes into your origin repo and, back in upstream, you can click Pull Request which will send your changes for review.

**Comment by VyacheslavMik** [comment]
@fommil I've got it. Thanks!
