### ISSUE TITLE
Focus option for sbt-command and sbt:command

### ISSUE THREAD

**Issue by tbje** [ensime/emacs-sbt-mode#46]
I have local changes allowing to pass an optional focus argument to sbt-command and sbt:command. 
This allows to optionally focus on the buffer by using *pop-to-buffer* instead of *display-buffer*. I like it for *ensime-sbt-do-run* and *ensime-sbt-do-console*. Would you like me to submit a pull request?

**Comment by hvesalai** [comment]
Pull requests are always welcome. Let's review it and then decide if it is something we want into master.

**Comment by hvesalai** [comment]
Duplicate of #47
