### ISSUE TITLE
I don't have my theme color using this mode.

### ISSUE THREAD

**Issue by mikefaille** [ensime/emacs-sbt-mode#48]
Known error ?

**Comment by hvesalai** [comment]
Not a known error and not something I can confirm.

Try to debug why this is so. The mode defines the faces `sbt:error`, `sbt:info` and `sbt:warning`, which inherit the basic faces `error`, `info` and `warning` respectively.

To see how a face is defined, use the `describe-face` command.

Check out where you have defined your colors and if you have really overriden the basic faces properly.
