### ISSUE TITLE
next-error buries SBT buffer

### ISSUE THREAD

**Issue by nloyola** [ensime/emacs-sbt-mode#50]
I'm using *sbt-mode* version 20160219.248 on Emacs 24.5.1 running on Ubuntu. 

Say I run `test:compile` in the SBT buffer, and the SBT buffer is using the whole frame with no other windows open. If I have compile errors or warnings, I press the keys that correspond to `next-error`, and the window is split vertically and my source code is shown on the window on the right with the cursor where the error is. If I press the keys for `next-error` again, and the error is in a different source code file, the SBT buffer is buried and gets replaced with the source code buffer. 

This behaviour is problematic because I can no longer see the error message for the second error. Why is the SBT buffer being buried? Is there an option to disable this? As I remember, previous versions of `sbt-mode` did not do this.

Thanks

**Comment by nloyola** [comment]
I can get the behaviour I want by wrapping `next-error`:

```emacs-lisp
(defun sbt:next-error ()
  (interactive)
  (sbt:switch-to-active-sbt-buffer)
  (next-error))
```

Can this be added to the package?

**Comment by nloyola** [comment]
Would using `advice` work better?

```emacs-lisp
(defun sbt:next-error (orig-fun &rest args)
  (if (derived-mode-p 'scala-mode)
      (sbt:switch-to-active-sbt-buffer))
  (apply orig-fun args))

(advice-add 'next-error :around #'sbt:next-error)
```

**Comment by hvesalai** [comment]
I'm using emacs 24.3.1 and cannot repeat this. So it must be a change in emacs, not sbt-mode. I'd suggest investigating this further instead of trying to quick-fix it.

**Comment by nloyola** [comment]
I figured out it must be my configuration. I started with a fresh config, only `sbt-mode` and `scala-mode2` packages installed, and `next-error` worked as expected.

Closing this issue.
