### ISSUE TITLE
Broken navigation from compilation error to source code when using ~compile 

### ISSUE THREAD

**Issue by VlachJosef** [ensime/emacs-sbt-mode#51]
Using `~compile` as command to be executed by `sbt-command` is breaking navigation links in compiler output in sbt buffer. Links are being broken whenever number of lines in source file change between consecutive saves of a file which triggers recompiling of source file.

Using `~` when running sbt command is crucial for reproducing this bug as this cause appending new output to existing sbt buffer. Procedures in compile.el which are processing output in sbt buffer assume that output in that buffer is generated by one run of the compiler, whereas when using `~` we are appending output from multiple runs of compiler which inevitably cause links to be broken.

Demonstration of this problem is recorded in this video: https://youtu.be/4NOV-WmNKKo

**Comment by hvesalai** [comment]
Duplicate of #32

**Comment by VlachJosef** [comment]
Closing this as it is really a duplicate of https://github.com/ensime/emacs-sbt-mode/issues/32

Since I'm using `sbt-hydra` for my day to day work, I'm not using `~` anymore in my workflow.

**Comment by fommil** [comment]
we should probably document that. A lot of people want to use the tilde commands and don't realise there is a better, more emacs, way.

**Comment by VlachJosef** [comment]
@fommil I will write some documentation for this one, as I agree that lots of people think tilde is only way how to get repeated command execution.
