### ISSUE TITLE
deprecate sbt-grep?

### ISSUE THREAD

**Issue by fommil** [ensime/emacs-sbt-mode#53]
@hvesalai just a thought, is there any reason for `sbt-grep` since https://github.com/bbatsov/projectile provides similar functionality but is not sbt specific.

**Comment by hvesalai** [comment]
I don't know. sbt-grep is a generic grep on all files in the project. Does projectile do the same? At least it seems it doesn't provide me with `sbt-find-usage` and `sbt-find-definition`, which are based on grep.

**Comment by fommil** [comment]
I use it for the former (it has multiple backends. ag is best on Linux, git-grep is best on windows) and I use its TAGS support for the latter.

Have you had a look at the Hacks page on ensime.org recently? It covers a bunch of stuff like this, even for cross language and Scala editing without ensime.

**Comment by VlachJosef** [comment]
I'm using `sbt-find-definition` quite a lot, since it can search places which are by design ignored by ag or git-grep. Places like `target/scala-2.11/src_managed`.

**Comment by fommil** [comment]
@VlachJosef you know you can tell projectile to look in those places? I should add this to the hacks page. I do it for `.log` files.

**Comment by VlachJosef** [comment]
Yes, I know that projectile also offers grep search. I only didn't delve into customizing that part of emacs yet. Although I would like to look into `sbt-find-definition` or projectile to make it more efficient, since out-of-the-box speed of search is quite slow.

**Comment by fommil** [comment]
projectile's search is super fast for me. For projectile to see some things that are excluded by git try this

```elisp
(setq
 ;; allows projectile to see .log files, even though git ignores them
 projectile-git-command "cat <(git ls-files -zco --exclude-standard) <(find . -name '*.log' -maxdepth 4 -print0)")

```

**Comment by VlachJosef** [comment]
wow, this is nice hack. Now I can see in the projectile `projectile-find-file` files which are ignored by git, but `projectile-grep` is not using that settings apparently.

**Comment by hvesalai** [comment]
I didn't bother with index files with `sbt-find-definitions` because I think developers have or at least soon will have SSD drives. With them indexing source files is really not needed. Besides the index files need to be kept up to date, which is a tricky thing to do efficiently.

**Comment by fommil** [comment]
I don't know what you mean by index files? Projectile uses an index for jumping to files, but not for searching. The index is definitely necessary for that, especially on Windows.

**Comment by fommil** [comment]
@VlachJosef oh, you want to be using `projectile-git-grep` (it's already on the hacks page). It's **way** faster than grep.

**Comment by hvesalai** [comment]
Yes, index for searching, like ETAGs, etc. Not needed when you have a Solid State Drive. Not at least on Linux.

**Comment by fommil** [comment]
I added a hack section for using `TAGS` too. That's useful even for the simple reason that it understands the difference between methods / classes, etc.
