### ISSUE TITLE
persistent command history

### ISSUE THREAD

**Issue by fommil** [ensime/emacs-sbt-mode#61]
I tend to use `*scratch*` as a place to store the common commands that I use in sbt in a larger project.

I wonder if perhaps we could have tighter integration with projectile to persist the sbt commands for a project across sessions. Maybe even an `ido`-compatible way to search that history.

**Comment by hvesalai** [comment]
Use sbt history. Meta p

**Comment by fommil** [comment]
Doesn't work for sbt-command. If sbt is already persisting the history that's good.
