### ISSUE TITLE
don't scroll the buffer to keep up with sbt output

### ISSUE THREAD

**Issue by fommil** [ensime/emacs-sbt-mode#70]
sometimes when I'm running an app or test I want to be able to move the point to a particular piece of text and stay there for a while. But as soon as some new output appears, `sbt-mode` always jumps to show it. It would be good to be able to disable this behaviour... I haven't figured out what is causing it yet.

**Comment by Trevoke** [comment]
@fommil is this issue still open? Looks like a PR was merged that fixes it?
