### ISSUE TITLE
ensime-sbt-switch crashes Ensime process

### ISSUE THREAD

**Issue by microamp** [ensime/emacs-sbt-mode#75]
Running `ensime-sbt-switch` crashes the running Ensime process with this error:
```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument markerp nil)
  comint-output-filter(#<process *sbt*<~/src/my-scala-project/>> "[info] Loading global plugins from /Users/microamp/.sbt/0.13/plugins\n")
```

I'm running
* Emacs 25.1.1 on OS X
* Scala 2.11.8
* sbt 0.13
* Emacs packages
  * `ensime-1.0.0` (from stable.melpa.org)
  * `scala-mode-20160813.304` (Also tried the stable version)
  * `sbt-mode-20160816.1353` (Also tried the stable version)

I wonder if it's a bug elsewhere. Please let me know if I need to provide more info. Thanks.

**Comment by fommil** [comment]
@microamp can you raise this with `ensime-emacs` please?
