### ISSUE TITLE
Can't interrupt a running job

### ISSUE THREAD

**Issue by Trevoke** [ensime/emacs-sbt-mode#77]
If I run `C-c C-c` which should run `comint-interrupt-subjob` I get the error "Text is read-only".

**Comment by fommil** [comment]
use `C-c C-z`

**Comment by fommil** [comment]
http://ensime.github.io/build_tools/sbt/#cancel-debugging-processes

**Comment by Trevoke** [comment]
Neither `C-c C-z` or `C-c C-v C-c C-c` or `C-c C-v C-c C-z` seem to allow me to interrupt a running test.

**Comment by fommil** [comment]
You mean `C-c C-z C-c C-c`?

That might mean you've not set up sbt correctly. Does it work from the command line? There should be docs about what you need to do in sbt at the above link. It "works for me". Mostly. Sometimes. (but it's usually sbt to blame).
