### ISSUE TITLE
Splitting `sbt:program-name` on spaces…

### ISSUE THREAD

**Issue by michalrus** [ensime/emacs-sbt-mode#79]
So in sbt-mode.el we have:

``` elisp
(sbt-command-line (split-string sbt:program-name " "))
[…]
(comint-exec (current-buffer) buffer-name (nth 0 sbt-command-line) nil (cdr sbt-command-line))
```

This disables me to set `sbt:program-name` to e.g. `"nix-shell -p openjdk7 --run 'exec sbt'"`, as the `'exec sbt'` part will be cut in half.

What if the user could provide their own list of arguments?

Thank you!

**Comment by fommil** [comment]
Sounds good, also relevant for windows users with sbt in Program Files or whatnot. Would you be interested in helping to fix this with an initial PR? Sorry this package has no tests :-(

**Comment by michalrus** [comment]
@fommil, sure! :-) Thank you.

So, at first look, the options are:

1. Check if `sbt:program-name` is a list, and if it is, bind it directly to `sbt-command-line`. Else, keep the current behavior of splitting it on spaces. Document that list possibility.
1. Add another `defcustom` with `sbt:command-line` list and if it’s non-nil, use this. If nil, use `sbt:program-name` as before.
1. Make `sbt:program-name` a list with one element by default (`sbt`) and use it as `sbt-command-line` above… This will break people’s configs.
1. …?

@fommil, which one do you want me to implement? =)

**Comment by fommil** [comment]
2 sounds good. Document why we have the old one and maybe spit out a warning if anybody is still setting it. Ensime uses it I think so may need updated too.
