### ISSUE TITLE
sbt-run-previous-command and last shell command

### ISSUE THREAD

**Issue by nloyola** [ensime/emacs-sbt-mode#80]
I'm not sure that I remember this correctly. But, it seems that with a previous version of sbt-mode, when I used `sbt-run-previous-command`, the last command I typed into the sbt shell would be run. With the latest version this is no longer the case. 

Should it work like this?

I'm using sbt-mode-20160914.818 in Emacs 25.1.1 on Ubuntu 16.04.

**Comment by fommil** [comment]
This should be working, can you please create a full reproduction and we'll reopen the ticket? I'm not observing this, but I tend to use sbt-command and this is the default behaviour.
