### ISSUE TITLE
sbt-run-previous-command does not execute the last shell command

### ISSUE THREAD

**Issue by nloyola** [ensime/emacs-sbt-mode#81]
If you type a command into the SBT shell and then execute `sbt-run-previous-command`, the command typed into the SBT shell is not the one executed.

I'm using sbt-mode-20160914.818 in Emacs 25.1.1 on Ubuntu 16.04.

I tested this by cloning this repository: https://github.com/mariussoutier/play-angular-require-seed. In Emacs I used the following commands:

1. `M-x sbt-start`
1. In the SBT shell I then type: `compile`
1. Then I type: `M-x eval-expression` and `(sbt:get-previous-command)`

Emacs then displays `test:compile`.

**Comment by fommil** [comment]
I meant for you to AAU this to the previous ticket, but this works too :-)

What can we do the help you debug this further? Have you read the contributing guide?

**Comment by nloyola** [comment]
It turns out this functionality was never there. But I figured out how to add it. I will create a pull request shortly.

Yes, I have read the contributing guide. I've also submitted a few commits in the past to this repository (back in April of 2014).

**Comment by fommil** [comment]
Cool, but like I said, I believe this is the intended behaviour of sbt-command so please do not add a new function if the feature is already there.

**Comment by fommil** [comment]
Or do you mean the previous to last command? If that is the case then perhaps something like a universal argument to sbt-command would be ideal. C-u M-x sbt-command could go one back.

**Comment by nloyola** [comment]
This is confusing. What is the intent of `sbt-previous-command` should it not be either the last command typed into the SBT shell, or the last command used with `sbt-command`?

**Comment by fommil** [comment]
I'm also confused, I'm not entirely sure what is broken or needed.

Let's try to reset :-)

Your minimal failing case looks like a bug in sbt:get-previous-command and you're saying you want an interactive function to run that again?

I guess it makes sense for sbt-command to only rerun sbt-commands (not shell inputs) so if you're saying that sbt-run-previous-command is broken because of the getter then i think you might be right. Also, it sounds similar to something I seen in #61

**Comment by nloyola** [comment]
The behaviour I would expect is as follows:

1. <kbd>M-x sbt-command</kbd> followed by `compile` runs the corresponding command,
1. <kbd>M-x sbt-run-previous-command</kbd> then runs the `compile` command,
1. User types `test:compile` into the SBT shell and the corresponding command executes,
1. <kbd>M-x sbt-run-previous-command</kbd> should then run the `test:compile` command.

The reason for this is that I would like to use the completion functionality provided within the SBT shell. For example, in the shell I type `testOnly com.`  and then press the <kbd>Tab</kbd> key to select from a list of completions. Once the command runs, I go back to editing code. When I'm done editing the code, I would like to execute the `testOnly` command I just typed into the SBT shell with <kbd>M-x sbt-command</kbd> (or to be more precise the keyboard shortcut).

I cannot get completion to work in this fashion if I use `sbt-command`.

If this is not the intent of <kbd>M-x sbt-run-previous-command</kbd> , then would it make sense to add this functionality with a different function?

**Comment by hvesalai** [comment]
Sure you have comman completion in `sbt-command`

**Comment by hvesalai** [comment]
you can even access the shell history from `sbt-command`

**Comment by hvesalai** [comment]
And yes, `sbt-run-previous-command` is designed to execute the previous command run by `sbt-command`, not the ones run in the sbt shell.

**Comment by nloyola** [comment]
@hvesalai Why can't it be both?

**Comment by hvesalai** [comment]
At least I use it to run a command I want to be run after I change code. Like `test:compile` or `testOnly`. So just like you. The only difference is that I run the command I want to repeat using `sbt-command` (which supports command completion, contrary to what you said above).

That leaves me free to run other commands in the shell without changing what happens with `sbt-run-prvious-command`

**Comment by nloyola** [comment]
I figured out that `sbt-command` is not working correctly for me because I have [Ivy](https://github.com/abo-abo/swiper) enabled. 

I will close this now since my use case is not valid.
