### ISSUE TITLE
Prevent scrolling of sbt output

### ISSUE THREAD

**Issue by hvesalai** [ensime/emacs-sbt-mode#91]
Lately I have been setting `comint-scroll-to-bottom-on-output` to nil before I start working. This is because when I do large refactoring, there are tens or even hundreds of errors and I want to start looking at them before the compilation has finished. However, without setting the variable to nil, the point would be moved to the end every time there is new output (i.e. more compilation errors).

I was wondering if I'm not alone and if we should change this behavior to be the default. It would work like this:

1. if the point is at the end of the buffer (i.e. at prompt), then new output is appended before the point and all works just like now (i.e. buffer scrolls with new output). For example, this would be the case if you typed the command to the sbt buffer.

2. while running a command / compiling, if you moved the point to an other place, it would stay there even if there was more output. This would happen, for example, when you hit `next-error` to move the point.

3. if you use `sbt-command` (`sbt-run-previous-command`), it clears the buffer and so the point is again at the end of the buffer and we are back to 1.

And always, `end-of-buffer` (usually bound to `M->`) would take you to step 1.

**Comment by hvesalai** [comment]
@fommil comments?

**Comment by fommil** [comment]
Yeah that's a really nice workflow. I think i tried to approximate this with intricate compile-mode settings. Maybe have a look at my config first to see if there are any relevant settings? I think a I'm getting the "stay at point behaviour"

That said, only "compilation-scroll-output 'first-error" comes to mind

https://github.com/fommil/dotfiles/blob/master/.emacs.d/init.el

I have trouble remembering my workflow when I'm not at my computer. I'll try to notice the exact behaviour today.

**Comment by hvesalai** [comment]
Hmm... I must test `compilation-scroll-output`. By the looks of it, it could be exactly what I wanted.

```
If you change the variable compilation-scroll-output to a non-nil value, the *compilation* buffer scrolls automatically to follow the output. If the value is first-error, scrolling stops when the first error appears, leaving point at that error. For any other non-nil value, scrolling continues until there is no more output. 
```

**Comment by hvesalai** [comment]
It didn't work and even if it did, I realize it's not what I want. I would like it to scroll with the output until I hit `next-error` and only then stick to that point, not automatically.

**Comment by fommil** [comment]
yeah, might be a useful thing in general for compile buffers!

**Comment by fommil** [comment]
this seems to work as expected when using sbt-command, because it clears the buffer first.

**Comment by hvesalai** [comment]
Ok, but if there is no objection, I'd would set `comint-scroll-to-bottom-on-output` to nil as the default for sbt buffer

**Comment by VlachJosef** [comment]
@hvesalai I wonder if you are aware of https://github.com/ensime/emacs-sbt-mode/pull/72

**Comment by yyadavalli** [comment]
If possible, how about switching the behavior when the command is prefixed i.e. `C-u M-x sbt-command` would not scroll the output, leaving the default scrolling when running `M-x sbt-command`

**Comment by fommil** [comment]
@VlachJosef yup, I'm using this and it's awesome! `(setq sbt:scroll-to-bottom-on-output nil)` my memory is getting worse and worse...
