### ISSUE TITLE
Question: how do I run integration tests using hydra?

### ISSUE THREAD

**Issue by noorul** [ensime/emacs-sbt-mode#98]
I would like to run projects/it:test using hydra

Is it possible to add this as user customization?

**Comment by hvesalai** [comment]
use `sbt-command` or customize `sbt:default-command`

**Comment by fommil** [comment]
@VlachJosef any thoughts?

**Comment by fommil** [comment]
(btw, it's best to use gitter for questions... much larger audience there)

**Comment by VlachJosef** [comment]
@fommil @noorul Running integration tests (ie. test with `it:` scope) with hydra is currently not possible. But it should be easy to add this functionality.

**Comment by fommil** [comment]
@noorul fancy sending a PR with support for this? we have a section http://ensime.org/editors/emacs/contributing/ on how to get started

**Comment by noorul** [comment]
@fommil https://github.com/ensime/emacs-sbt-mode/pull/99
